"""initial schema

Revision ID: a87b526949f3
Revises: c36f072176b6
Create Date: 2026-05-21 01:48:45.075065

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a87b526949f3"
down_revision: str | Sequence[str] | None = "c36f072176b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coaches",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("bio_short", sa.String(length=500), nullable=False),
        sa.Column("bio_long", sa.String(), nullable=False),
        sa.Column("headshot_url", sa.String(length=500), nullable=True),
        sa.Column("calendly_url", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "packages",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("NAVIGATOR", "ARCHITECT", "ACCELERATOR", "GROUP", name="package_tier"),
            nullable=False,
        ),
        sa.Column(
            "pricing_model",
            sa.Enum("SUBSCRIPTION_MONTHLY", "ONE_TIME", name="package_pricing_model"),
            nullable=False,
        ),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("starting_from", sa.Boolean(), nullable=False),
        sa.Column("stripe_product_id", sa.String(length=120), nullable=True),
        sa.Column("stripe_price_id", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "resource_downloads",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("resource_slug", sa.String(length=120), nullable=False),
        sa.Column("download_token", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posthog_distinct_id", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("download_token"),
    )
    op.create_index(
        op.f("ix_resource_downloads_email"), "resource_downloads", ["email"], unique=False
    )
    op.create_table(
        "stripe_events",
        sa.Column("stripe_event_id", sa.String(length=120), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_event_id"),
    )
    op.create_table(
        "waitlist_entries",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("current_role", sa.String(length=200), nullable=False),
        sa.Column("years_of_experience", sa.String(length=40), nullable=False),
        sa.Column("biggest_challenge", sa.String(), nullable=False),
        sa.Column("linkedin_profile", sa.String(length=500), nullable=True),
        sa.Column("coach_preference", sa.String(length=40), nullable=True),
        sa.Column("workshop_interests", sa.JSON(), nullable=False),
        sa.Column("posthog_distinct_id", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_waitlist_entries_email"), "waitlist_entries", ["email"], unique=False)
    op.create_table(
        "leads",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("source_page", sa.String(length=200), nullable=True),
        sa.Column("posthog_distinct_id", sa.String(length=120), nullable=True),
        sa.Column("assigned_coach_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "CONTACTED", "QUALIFIED", "BOOKED", "PAID", "LOST", name="lead_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_coach_id"],
            ["coaches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_email"), "leads", ["email"], unique=False)
    op.create_table(
        "quiz_responses",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("matched_coach_id", sa.Uuid(), nullable=True),
        sa.Column("posthog_distinct_id", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_coach_id"],
            ["coaches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_responses_email"), "quiz_responses", ["email"], unique=False)
    op.create_table(
        "success_stories",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("client_name", sa.String(length=200), nullable=False),
        sa.Column("client_role_before", sa.String(length=200), nullable=True),
        sa.Column("client_role_after", sa.String(length=200), nullable=True),
        sa.Column("client_company_after", sa.String(length=200), nullable=True),
        sa.Column("headshot_url", sa.String(length=500), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("story_short", sa.String(), nullable=False),
        sa.Column("story_long", sa.String(), nullable=True),
        sa.Column("coach_id", sa.Uuid(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "bookings",
        sa.Column("calendly_event_uri", sa.String(length=500), nullable=False),
        sa.Column("coach_id", sa.Uuid(), nullable=True),
        sa.Column("invitee_email", sa.String(length=320), nullable=False),
        sa.Column("invitee_name", sa.String(length=200), nullable=True),
        sa.Column("event_type", sa.String(length=200), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "COMPLETED", "CANCELED", "NO_SHOW", name="booking_status"),
            nullable=False,
        ),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calendly_event_uri"),
    )
    op.create_index(op.f("ix_bookings_invitee_email"), "bookings", ["invitee_email"], unique=False)
    op.create_table(
        "payments",
        sa.Column("stripe_payment_intent_id", sa.String(length=120), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=120), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=120), nullable=True),
        sa.Column("stripe_checkout_session_id", sa.String(length=120), nullable=True),
        sa.Column("coach_id", sa.Uuid(), nullable=True),
        sa.Column("package_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCEEDED", "FAILED", "REFUNDED", name="payment_status"),
            nullable=False,
        ),
        sa.Column("raw_event", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_payment_intent_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_index(op.f("ix_bookings_invitee_email"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_table("success_stories")
    op.drop_index(op.f("ix_quiz_responses_email"), table_name="quiz_responses")
    op.drop_table("quiz_responses")
    op.drop_index(op.f("ix_leads_email"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_waitlist_entries_email"), table_name="waitlist_entries")
    op.drop_table("waitlist_entries")
    op.drop_table("stripe_events")
    op.drop_index(op.f("ix_resource_downloads_email"), table_name="resource_downloads")
    op.drop_table("resource_downloads")
    op.drop_table("packages")
    op.drop_table("coaches")
    # ### end Alembic commands ###
